import turtle
import time

screen = turtle.Screen()

eye = turtle.Turtle()
eye.width(3)
eye.speed(0)
eye.hideturtle()
eye.setpos(0,0)
eye.pendown()
eye.forward(35)
eye.right(5)
eye.forward(20)
eye.left(60)
eye.forward(4)
eye.left(75)
eye.forward(10)
eye.right(10)
eye.forward(20)
eye.left(40)
eye.forward(15)
eye.left(10)
eye.width(4)
eye.forward(10)
eye.left(10)
eye.forward(10)
eye.left(30)
eye.forward(20)
eye.left(20)
eye.forward(10)
eye.right(40)
eye.width(5)
eye.forward(30)
eye.right(10)
eye.forward(20)
eye.left(80)
eye.forward(7)
eye.left(105)
eye.width(4)
eye.forward(30)
eye.right(15)
eye.forward(20)
eye.setpos(0,0)
eye.penup()
eye.setpos(18,18)
eye.pendown()
eye.width(35)
eye.forward(1)
eye.penup()
eye.setpos(20,-2)
eye.width(7)
eye.pendown()
eye.right(120)
eye.forward(20)
eye.width(6)
eye.right(10)
eye.forward(15)
eye.right(15)
eye.forward(10)
eye.right(20)
eye.forward(5)
eye.width(4)
eye.right(20)
eye.forward(5)
eye.right(30)
eye.forward(5)
eye.width(2)
eye.right(30)
eye.forward(3)
eye.penup()
eye.setpos(25,-2)
eye.pendown()
eye.right(196)
eye.width(10)
eye.forward(8)
eye.width(9)
eye.forward(7)
eye.width(8)
eye.forward(7)
eye.width(6)
eye.forward(7)
eye.width(5)
eye.forward(6)
eye.penup()
eye.setpos(55,45)
eye.left(240)
eye.pendown()
eye.width(6)
eye.forward(20)
eye.left(15)
eye.forward(25)
eye.left(15)
eye.width(7)
eye.forward(20)
eye.left(20)
eye.forward(15)
eye.left(10)
eye.width(8)
eye.forward(10)
eye.left(10)
eye.forward(10)
eye.right(10)
eye.width(7)
eye.forward(10)
eye.right(10)
eye.width(6)
eye.forward(10)
eye.right(20)
eye.width(5)
eye.forward(20)

eye.penup()
eye.setpos(-68,8)
eye.pendown()
eye.right(175)
eye.forward(30)
eye.left(10)
eye.width(7)
eye.forward(15)



t1= turtle.Turtle()
font_style = ("Times New Roman", 25, "normal")
t1.hideturtle()
t1.penup()
t1.goto(0,-150)
t1.pendown()
t1.write("LOADING...", font=font_style, align="center")




dot = turtle.Turtle()

dot.penup()
dot.speed(5)
dot.hideturtle()
dot.setpos(-10,110)
dot.width(10)
dot.pendown()
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.speed(1)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.speed(100)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.speed(1)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.speed(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.speed(1)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.speed(0)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)
dot.right(6)
dot.forward(10)

time.sleep(.2)
t1.clear()

time.sleep(.2)

t2= turtle.Turtle()
font_style = ("Times New Roman", 25, "normal")
t2.hideturtle()
t2.penup()
t2.goto(0,-150)
t2.pendown()
t2.write("click to continue", font=font_style, align="center")

screen.exitonclick()









turtle.done()